Uncaught TypeError: Cannot read property 'socket' of undefined (#18)
* bugfix: Cannot read property 'socket' of undefined

error: Uncaught TypeError: Cannot read property 'socket' of undefined

description:
handle connection error first before attempting to get result.socket
result will be undefined if there is a connection error, and instead
of handling the connection error, we will crash on trying to reference
socket from an 'undefined' result object

* @talmobi This line just needs to be moved under the check for err. No
need for a try/catch, result.socket will always be defined if err is
null.

ref: https://github.com/TooTallNate/node-socks-proxy-agent/pull/18#issuecomment-381253168